apiVersion: v1
kind: ConfigMap
metadata:
  name: kplabs-ambassador-config
data:
  haproxy.cfg: |-
    global
        daemon
        maxconn 256

    defaults
        mode http
        timeout connect 5000ms
        timeout client 50000ms
        timeout server 50000ms

    listen http-in
        bind *:80
        server server1 127.0.0.1:9080 maxconn 32

---

apiVersion: v1
kind: Pod
metadata:
  name: ambassador
spec:
  containers:
  - name: haproxy-container
    image: haproxy:1.7
    volumeMounts:
    - name: config-volume
      mountPath: /usr/local/etc/haproxy
  - name: kplabs-nginx
    image: mykplabs/kubernetes:nginx
  volumes:
  - name: config-volume
    configMap:
      name: kplabs-ambassador-config

---

apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: curl-container
    image: yauritux/busybox-curl
    command: ['sh', '-c', 'while true; do sleep 3600; done']
